### ISSUE TITLE
Some items return "Not Found" while others still work, no errors reported

### ISSUE THREAD

**Issue by yatahaze** [burke-software/django-mass-edit#109]
Two new batches of records added to our system since updating to Django 4 and the latest version of django-mass-edit as of now.

- Editing anything on these two big sets of data returns "not found" error.
- I have no logs or error messages to reference.
- I can manually make new records and assign to the same batch of records, no issues there.
- I can go on my test server, make new records that work just fine.
- Regular edit functions seem to work fine.

What can I do to debug this?

**Comment by PetrDlouhy** [comment]
@yatahaze Can you please include some screenshots demonstrating the problem?

**Comment by yatahaze** [comment]
I forgot I even posted this. I haven't had any problems since. My best guess is I spaced and forgot to run some migrations. (Closing since I haven't had any issues since.)
