### ISSUE TITLE
Alter look-and-feel of mass edit form?

### ISSUE THREAD

**Issue by gamesbook** [burke-software/django-mass-edit#30]
I'd like to find some way to change the appearance of the mass-edit form.  I am using django-suit to customise the admin, and this package uses Bootstrap for the forms.

So, for example, a mass-edit form looks like this:
![mass](https://cloud.githubusercontent.com/assets/354027/3713259/c0645334-155d-11e4-9f6b-fbbcb0a60ae7.png)

Whereas the normal admin form looks like this:
![normal](https://cloud.githubusercontent.com/assets/354027/3713266/ec5b7422-155d-11e4-9ef6-349dcb9c9b24.png)

**Comment by bufke** [comment]
Cleaning up tickets - pull requests welcome.

**Comment by gamesbook** [comment]
So, no plans for Bootstrap compatibility? Given its widespread usage, I thought this might enhance mass-edit.
