### ISSUE TITLE
Incorrect redirection after mass editing

### ISSUE THREAD

**Issue by d33tah** [burke-software/django-mass-edit#39]
I just installed django-mass-edit, which basically boiled down to mentioning it in urls.py and settings.py. Mass editing works fine, but after the operation, I get redirected to '/admin/modelname' instead of '/admin/appname/modelname'. How can I fix that?

**Comment by bufke** [comment]
Thanks, no idea when this started happening. Rewrote the reverse url logic.

**Comment by d33tah** [comment]
Could you push a release with the bugfix?

**Comment by bufke** [comment]
Done - would appreciate testing
