### ISSUE TITLE
Push to pypi to fix RemovedInDjango19Warning

### ISSUE THREAD

**Issue by ffedoroff** [burke-software/django-mass-edit#51]
After I add 'massadmin' into INSTALLED_APPS I got that error:
```
.venv/local/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

.venv/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py:159: RemovedInDjango19Warning: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class ContentType(models.Model):
```

**Comment by kierun** [comment]
All you have to do is change:
       `django.contrib.admin.util import unquote`
to
       `django.contrib.admin.utils import unquote`
on line 36 of massadmin.py

I would submit a patch but really this is way too simple. ^_~

**Comment by bufke** [comment]
As soon as I get a chance I'll push to pypi https://github.com/burke-software/django-mass-edit/pull/48

If anyone wants to help maintain please let me know. I'm just going to quickly sanity check git master and push a new release. It's very easy to do.

**Comment by bufke** [comment]
2.5 is released.
