### ISSUE TITLE
Handling long drop-down lists

### ISSUE THREAD

**Issue by gamesbook** [burke-software/django-mass-edit#53]
dme is a very useful tool, but as our database has grown, so has the length of many of the drop-down lists & we have had to disable some to allow for reasonable page load times.  Could there be some consideration given to allow dme to support django-selectable (http://django-selectable.readthedocs.org/en/latest/index.html) which allow for incremental lookups and thereby avoids the problems of loading large lists at page creation time?  Thanks!

**Comment by bufke** [comment]
I'd accept a pull request to add compatibility as long as it doesn't require everyone install django-selectable. There are many ways to do what you are suggesting - django-grappelli has a lookup thing for this type of problem too. Personally I prefer django-autocomplete-light.

**Comment by gamesbook** [comment]
I don't want to re-invent any wheels.  At some point libraries will need/have to accept dependencies on others - django-selectable has worked well for us and is straightforward to work with in the admin.  I suppose one could make use of a library switchable... but if no one else has encountered this issue, there is little point in working on a patch.

**Comment by gamesbook** [comment]
When upgrading our project we decided to switch to `django-autocomplete-light`
