### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by PetrDlouhy** [burke-software/django-mass-edit#54]
There is warning about future incompatibility with Django 1.10
```
/env/lib/python3.4/site-packages/massadmin/urls.py:7: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
```

**Comment by bufke** [comment]
Hoping to give this project some attention next month or so. Have some deadlines right now and 1.10 is scheduled for August 2016. Feel free to take on this change too - I only want to support versions of Django that still get updates. 1.8 and 1.9 now. We can put up a notice if we break compatibility to use some earlier version.

**Comment by PetrDlouhy** [comment]
Well, this urlpatterns issue is very easy - check PR #58. But there are more issues, which I don't want to spend too much time with.

This one even don't break any compatibility.
I also added Django development version to Travis in allow-failures mode.
