### ISSUE TITLE
Updating Individual Objects

### ISSUE THREAD

**Issue by keehun** [burke-software/django-mass-edit#55]
Hi Burke Software,

This is a lovely app. I'm not necessarily reporting a bug, or even requesting a feature change. I'm trying to find an app, like this mass edit app, that lets me select a set of objects and certain fields, then it presents me with a long page with all the selected objects and the selected fields so I can do quick data entry. I'm sure this is possible with coding, but is there an app out there you know that would do this?

As far as I'm aware, django-mass-edit bulk-edits all the selected objects with the exact same data entered in the form. Correct?

Thank you for both reporting and mass-edit!

keehun

**Comment by bufke** [comment]
You are correct about mass-edit's abilities. You could get something semi like what you describe with django Admin's list_editable. If your selection criteria can match a admin filter it might work. Or you could make your own admin action and view for this type of thing. It wouldn't be a huge task though it's by no means trivial. I've learned a lot about django maintaining this project and django-report-builder. It sounds like a project that could easily be it's own drop in django app.

Another option would be to export the data to a spreadsheet and reimport it.

In any case related fields could get tricky. Good luck.
