### ISSUE TITLE
No integration with custom admin site

### ISSUE THREAD

**Issue by belugame** [burke-software/django-mass-edit#57]
I'm on Python 3 with Django 1.8 and noticed that I can see mass-edits admin action in the drop down of change lists only if I use Django's default admin site. When I start using a custom admin site, it is no longer there and I can't mass-edit any model.

**Comment by bufke** [comment]
I'm very open to suggestions and pull requests but I can't support every possible scenario. If you can think of a way to change the templates to better support custom admin changes let me know and I'll reopen the issue.
