### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by frnhr** [burke-software/django-mass-edit#81]
I’m using this app in production and have an interest in keeping it updated and maybe evolving as well. So thank you for a great app @bufke et al.

There is a [PR](https://github.com/burke-software/django-mass-edit/pull/80) that I made 6 months ago which still got no reply. I totally understand the limitations of 24 hours in a day, believe me! I’m just wondering about the state of this app and if there is anything I can do to help keep the app alive.

**Comment by bufke** [comment]
Hello - @PetrDlouhy and I maintain this project. I can speak only for myself - I'm happy to help out a little here and there but I have no paying clients currently supporting development of this and my time is super limited. If you or anyone would like to be a maintainer let me know. I'm also a contractor, if anyone wants to pay me to do something, I'm happy to do that as well.

**Comment by bufke** [comment]
I'm going to close this as answered and it looks like PetrDlougy has responded to the PR in question. Could always use help on maintenance.
