### ISSUE TITLE
KeyError 'has_view_permission' during template rendering

### ISSUE THREAD

**Issue by fim13** [burke-software/django-mass-edit#83]
Django version: 2.1.4
Python Version: 3.6.0
KeyError:
'has_view_permission' is missing "In template .../django/contrib/admin/templates/admin/base.html, error at line 58"

Django 2.1 added a view permission to the default permissions.

**Comment by PetrDlouhy** [comment]
@fim13 Are you sure, you use newest PyPI version `3.2.0`? I use `django-mass-edit` with Django `2.2.9` without any problem?
Please describe, what you have done before this error.

**Comment by fim13** [comment]
@PetrDlouhy I do, following my Pipfile.lock:
```
   "django-mass-edit": {
          "hashes": [
                      ...
          ],
          "index": "pypi",
          "version": "==3.2.0"
      },
```

**Comment by fim13** [comment]
Strange I added 'has_view_permission' to context and now I get 'has_editable_inline_admin_formsets' missing – something seems strange.

**Comment by fim13** [comment]
Found the problem, DjangoObjectActions from django_object_actions sets 'change_form_template' too, which isn't compatible, any ideas besides not using django_object_actions.

**Comment by danialmalik** [comment]
@fim13 were you able to find a workaround? I am facing the same issue. I have `change_form_template` for some of my model admins and am getting the same error.
