### ISSUE TITLE
Custom Admin: Mass edit not working due to bad reverse

### ISSUE THREAD

**Issue by victor-lenoir** [burke-software/django-mass-edit#87]
Hello,

Love the package but i'm having issues with it when using it with a custom admin.
In massadmin/massadmin.py line 152: 
If
`        redirect_url = reverse('admin:{}_{}_changelist'.format(
            self.model._meta.app_label,
            self.model._meta.model_name,
        ))
`

Could become

`redirect_url = reverse('{}:{}_{}_changelist'.format(
            self.admin_site.name,
            self.model._meta.app_label,
            self.model._meta.model_name,
        ))
`

To fully handle custom admin that would be great!
Do you want me to make a PR?

Cheers!

**Comment by PetrDlouhy** [comment]
Hi Victor,

seems like useful change. Please make the PR.

**Comment by PetrDlouhy** [comment]
I already fixed this in https://github.com/burke-software/django-mass-edit/commit/8a2fbe01186e1277c19795d2c9053d76186cefa6 even with test.
