### ISSUE TITLE
Use of session-based URLs?

### ISSUE THREAD

**Issue by gamesbook** [burke-software/django-mass-edit#91]
The docs say:
```
To avoid problems with too long URL when editing large number of objects, 
the list of objects will be stored in session and the URL will look like this:

   /admin/myapp/mymodel-masschange/session-c81e728d9d4c2f636f067f89cc14862c/

This threshold can be changed in settings:

MASSEDIT = {
    'SESSION_BASED_URL_THRESHOLD': 0,
}

To always use the session-based URLs, simply put in value 0
```
I have made the change as indicated (in `settings.py`), but after a restart, I still get the long list of object IDs and not the session ID as shown.

What else needs to be changed to get this to work?

**Comment by PetrDlouhy** [comment]
@gamesbook I really don't know. I have tried this, and it works as indicated on the newest `@master` code.

**Comment by gamesbook** [comment]
Is there a pip release version number I can  try  (I am working with an older version of Django)?

**Comment by PetrDlouhy** [comment]
The version 3.2.0 should be compatible with Django 1.11. It seems, that nothing has changed regarding the session-based URLs, but please test the issue with latest version.

**Comment by PetrDlouhy** [comment]
Is there any problem with the newest version? If yes, please reopen this.
